### ISSUE TITLE
TDDium projects are not exported correctly

### ISSUE THREAD

**Issue by tay** [pivotal/projectmonitor#52]
When I export a TDDium project, the markup is missing all the TDDium attributes, so that importing it doesn't work.

Is exporting TDDium on your roadmap? It would be great if you would be able to import/export all supported project types.

```
projects:
- guid: faf2201b-e589-4ee7-9928-d8cd03d9382c
  name: o2.1-airbnb
  deprecated_feed_url:
  auth_username: ''
  auth_password: ''
  enabled: true
  type: TddiumProject
  aggregate_project_id:
  deprecated_latest_status_id:
  code: O2
  tracker_project_id: ''
  tracker_auth_token: ''
  cruise_control_rss_feed_url:
  jenkins_base_url:
  jenkins_build_name:
  team_city_base_url:
  team_city_build_id:
  team_city_rest_base_url:
  team_city_rest_build_type_id:
  travis_github_account:
  travis_repository:
  webhooks_enabled: false
  tag_list: []
```
