### ISSUE TITLE
pulse returns 500 for CircleCI webhook

### ISSUE THREAD

**Issue by brendanbenson** [pivotal/projectmonitor#54]
We have a project set up in pulse to use webhooks for the build board in the Boulder office. However, when CircleCI pings pulse on a successful build, it gets a 500 error:

![screen shot 2014-08-22 at 3 18 23 pm](https://cloud.githubusercontent.com/assets/866866/4017611/212b1952-2a42-11e4-925a-f5a31f6e144e.png)

Our circle.yml is as follows:

```yml
notify:
  webhooks:
    - url: http://pulse.pivotallabs.com/projects/our-guid/status
```
